---
# tasks file for ansible-deploy-dotfiles/

- include: vim.yml

- name: Place tmux.conf
  copy: src=tmux.conf dest="{{ homedir }}/.tmux.conf"

- include: debian.yml
  when: ansible_distribution == "Debian"

- include: macosx.yml
  when: ansible_distribution == "MacOSX"
